version:  "3.0"
services:
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.157.0
    restart: always 
    volumes:
      - ./config/otel-collector/otel-collector-config-${env}.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
      - victoria-traces
      - victoria-logs
      - victoria-metrics 

  victoria-traces:
    image: victoriametrics/victoria-traces:v0.10.0
    restart: always
    command:
      - "--retentionPeriod=8w"
      - "--storageDataPath=/victoria-traces-data"
      - "--httpListenAddr=:10428"
      - "--servicegraph.enableTask=true"
    ports:
      - 10428:10428/tcp
    volumes:
      - ./volumes/victoria-traces-data:/victoria-traces-data

  victoria-logs:
    image: victoriametrics/victoria-logs:latest
    restart: always
    command:
      - "--retentionPeriod=8w"
      - "--storageDataPath=/victoria-logs-data"
      - "--httpListenAddr=:9428"
      - "--loggerLevel=INFO"
    ports:
      - 9428:9428/tcp
    volumes:
      - ./volumes/victoria-logs-data:/victoria-logs-data

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.144.0
    command:
      - "--retentionPeriod=8w"
      - "--storageDataPath=/victoria-metrics-data"
      - "--httpListenAddr=:8428"
      - "--opentelemetry.usePrometheusNaming=true"
      - "--enableMetadata=true"
    ports:
      - "8428:8428"
    volumes:
      - ./volumes/victoria-metrics-data:/victoria-metrics-data
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.1.0-24320339380
    restart: always
    ports:
      - 3000:3000/tcp
    volumes:
      - ./volumes/grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./dashboards:/var/lib/grafana/dashboards 
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/ldap.toml:/etc/grafana/ldap.toml
    depends_on:
      - otel-collector
    environment:
      GF_INSTALL_PLUGINS: "victoriametrics-metrics-datasource,victoriametrics-logs-datasource"
      GRAFANA_BIND_DN: ${GRAFANA_BIND_DN}
      GRAFANA_BIND_PASSWORD: ${GRAFANA_BIND_PASSWORD}
      GRAFANA_LDAP_HOST: ${GRAFANA_LDAP_HOST}
